name: TAC5Remote_iOS_App
options:
  minimumXcodeGenVersion: 2.39.0
packages:
  TAC5Core:
    path: .
targets:
  TAC5Remote_iOS_App:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App/Sources
      - path: App/Resources
    dependencies:
      - package: TAC5Core
        product: TAC5Core
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: 8Q774J3K2P
        INFOPLIST_FILE: App/Resources/Info.plist
        MARKETING_VERSION: 1.0
        PRODUCT_BUNDLE_IDENTIFIER: hu.moderato.tac5remote.ios
        SWIFT_VERSION: 5.10
        TARGETED_DEVICE_FAMILY: "1,2"
schemes:
  TAC5Remote_iOS_App:
    build:
      targets:
        TAC5Remote_iOS_App: all
